# Generated by Django 4.1.5 on 2023-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='./csv')),
                ('hash', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'CSV',
                'verbose_name_plural': 'CSVs',
            },
        ),
    ]
