# Generated by Django 4.1.5 on 2023-02-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='hash',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
