# Generated by Django 4.1.5 on 2023-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_csv_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
