# Generated by Django 4.1.5 on 2023-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_csv_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='id',
        ),
        migrations.AlterField(
            model_name='csv',
            name='hash',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
