# Generated by Django 4.1.5 on 2023-02-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_csv_id_alter_csv_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='features',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
