# Generated by Django 4.1.5 on 2023-02-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_csv_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='csv',
            new_name='file',
        ),
    ]
